### ISSUE TITLE
don't working

### ISSUE THREAD

**Issue by denic23123** [donno2048/DDos#4]
I have an error. I use the first code.

**Comment by donno2048** [comment]
On which line? What is the traceback? What operating system are you using? Did you get it from GitHub or from PyPI (`pip3 install DDos==1.0.1` or `pip3 install git+https://github.com/donno2048/DDos`)?

**Comment by denic23123** [comment]
After I've entered the site, I'm asked to re-enter it many times. I have windows and downloaded from pypi
![error](https://user-images.githubusercontent.com/90136699/132125056-7fc7ebbb-51ae-4718-9a2c-1b4016b95a5c.jpg)

**Comment by donno2048** [comment]
Try just using
```py
from DDos import DDos
DDos(URL)
```

**Comment by denic23123** [comment]
> 
> 
> Try just using
> 
> ```python
> from DDos import DDos
> DDos(URL)
> ```

I get a very big mistake

**Comment by donno2048** [comment]
Could you elaborate? If the log is really big you can create a public gist or a Pastebin and send a link...

**Comment by denic23123** [comment]
Which version of python are you using?

**Comment by donno2048** [comment]
`3.9.5`

**Comment by denic23123** [comment]
> 
> 
> Could you elaborate? If the log is really big you can create a public gist or a Pastebin and send a link...

Here https://github.com/denic23123/error

**Comment by donno2048** [comment]
I can't actually reproduce the issue I have a `fix` branch that might fix the issue even though it compromised the multiprocessing which makes everything worse **and** accidentally build upon version `1.0.2` and not `1.0.1` which is unstable...

You can install it directly using

```sh
pip3 install https://github.com/donno2048/DDos/archive/fix.zip
```

Even though because I cannot reproduce the issue, I don't know whether it fixes it, and the new branch won't be reliable.

**Comment by donno2048** [comment]
Closing as stale
